### ISSUE TITLE
Browser Detection

### ISSUE THREAD

**Issue by Not-a-Tyler** [EugeneSunrise/Invise#3] opened 2023-11-18 06:44 UTC
https://pixelscan.net/ detects this as an anti-detect browser

**Comment by EugeneSunrise** [comment] 2023-11-18 06:56
I see it, will be fixed in the next update

**Comment by EugeneSunrise** [comment] 2023-11-18 07:36
Looked what could be the cause, user agent, change it to another one like Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0.0 Safari/537.36
![img-2023-11-18-17-35-38](https://github.com/EugeneSunrise/Invise/assets/56397706/11be3131-59a3-4e37-88e6-40573ba6dc53)

**Comment by EugeneSunrise** [comment] 2023-11-18 07:37
Let me know if it's okay

**Comment by Not-a-Tyler** [comment] 2023-11-18 08:21
Wow, thanks! that was fast. Is there any way to connect this to like selenium or undetected chromedriver? I would like to try to automate scripts with this for account generation.

**Comment by EugeneSunrise** [comment] 2023-11-18 08:34
invise based on cefsharp, for automatization with cefsharp(cefsharp includes chromedriver itself) need to use AngleSharp(Parsing, exec some functions etc.) and execution js scripts with EvaluateScriptAsync() and Browser.ExecuteScriptAsync, selenium connection doesn't make sense

**Closed** 2023-11-24 05:45 UTC
